import { useEffect, useRef, useState } from "react";
import { BrainCircuit, Send } from "lucide-react";

type Message = {
  role: "ai" | "user";
  text: string;
  time: string;
};

export default function AICopilot() {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: "ai",
      text: "👋 Hi! I'm PlaceMentor AI. Ask me anything about resumes, coding, interviews, communication, or placements.",
      time: "Now",
    },
  ]);

  const [input, setInput] = useState("");

  const messagesEndRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({
      behavior: "smooth",
    });
  }, [messages]);

  const handleSend = () => {
    if (!input.trim()) return;

    const userMessage: Message = {
      role: "user",
      text: input,
      time: new Date().toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit",
      }),
    };

    setMessages((prev) => [...prev, userMessage]);

    setInput("");

    // Temporary AI response
    setTimeout(() => {
      const aiReply: Message = {
        role: "ai",
        text: "🚀 Backend integration coming soon. This response will be generated by PlaceMentor AI.",
        time: new Date().toLocaleTimeString([], {
          hour: "2-digit",
          minute: "2-digit",
        }),
      };

      setMessages((prev) => [...prev, aiReply]);
    }, 700);
  };

  return (
    <div className="min-h-screen px-6 py-10">

      <div className="max-w-6xl mx-auto space-y-10">

        {/* Hero */}

        <div className="text-center space-y-6">

          <div className="inline-flex items-center rounded-full border border-primary/20 bg-primary/10 px-4 py-2 text-sm text-primary">
            🤖 AI Career Coach · Always On
          </div>

          <h1 className="text-5xl md:text-6xl font-bold tracking-tight text-white">
            AI Copilot
          </h1>

          <p className="max-w-2xl mx-auto text-lg text-muted-foreground">
            Your personal AI career strategist. Ask anything related to
            placements, coding, resumes, communication, or interviews.
          </p>

          <div className="flex flex-wrap justify-center gap-3">

            {[
              {
                emoji: "⚡",
                label: "Instant Feedback",
              },
              {
                emoji: "🎯",
                label: "Role Specific",
              },
              {
                emoji: "💬",
                label: "24/7 AI Assistant",
              },
            ].map((item) => (
              <div
                key={item.label}
                className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-white backdrop-blur-md"
              >
                {item.emoji} {item.label}
              </div>
            ))}

          </div>

        </div>

        {/* Chat Container */}

        <div className="flex justify-center">

          <div className="w-full max-w-3xl h-[75vh] rounded-3xl border border-white/10 bg-white/5 backdrop-blur-xl flex flex-col">

            {/* Header */}

            <div className="flex items-center gap-3 px-6 py-4 border-b border-white/10">

              <div className="relative flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-purple-600 to-blue-600">

                <BrainCircuit className="h-5 w-5 text-white" />

                <span className="absolute -top-0.5 -right-0.5 h-2.5 w-2.5 rounded-full bg-emerald-400 border-2 border-[#0f0f14]" />

              </div>

              <div>

                <h2 className="text-white font-semibold">
                  PlaceMentor AI
                </h2>

                <p className="text-xs text-emerald-400">
                  Online • Ready to help
                </p>

              </div>

            </div>            {/* Messages */}

            <div className="flex-1 overflow-y-auto px-6 py-6 space-y-5">

              {messages.map((msg, index) => (
                <div
                  key={index}
                  className={`flex gap-3 ${
                    msg.role === "user"
                      ? "justify-end"
                      : "justify-start"
                  }`}
                >

                  {msg.role === "ai" && (
                    <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-gradient-to-br from-purple-600/40 to-blue-600/40 border border-purple-500/20 flex-shrink-0">
                      <BrainCircuit className="h-4 w-4 text-purple-300" />
                    </div>
                  )}

                  <div
                    className={`max-w-[75%] flex flex-col ${
                      msg.role === "user"
                        ? "items-end"
                        : "items-start"
                    }`}
                  >

                    <div
                      className={`rounded-2xl px-4 py-3 text-sm leading-relaxed whitespace-pre-wrap ${
                        msg.role === "ai"
                          ? "bg-white/10 border border-white/10 text-white rounded-tl-sm"
                          : "bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-tr-sm"
                      }`}
                    >
                      {msg.text}
                    </div>

                    <span className="mt-1 text-[10px] text-muted-foreground">
                      {msg.time}
                    </span>

                  </div>

                </div>
              ))}

              <div ref={messagesEndRef} />

            </div>

            {/* Input */}

            <div className="border-t border-white/10 p-5">

              <div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 px-4 py-3">

                <input
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") {
                      handleSend();
                    }
                  }}
                  placeholder="Ask your AI coach anything..."
                  className="flex-1 bg-transparent outline-none text-white placeholder:text-gray-400"
                />

                <button
                  onClick={handleSend}
                  className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-r from-purple-600 to-blue-600 hover:scale-105 transition-transform"
                >
                  <Send className="h-4 w-4 text-white" />
                </button>

              </div>

              <p className="mt-2 text-center text-[11px] text-gray-500">
                PlaceMentor AI may make mistakes. Please verify important career advice.
              </p>

            </div>

          </div>

        </div>

      </div>

    </div>
  );
}